# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zeroed E-Kiln File
email: ilzolende@gmail.com
description: The currently art-centric website of Ilzolende Kiefer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ilzolende.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: ilzolende
author: Ilzolende Kiefer

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
collections:
  recordings:
  art:
  mesolexia:
    output: true